# mypy: disable-error-code="import-untyped,no-untyped-call"
"""Generate Phase 2 activation characterization reports."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import torch

from cvnn.analysis import (
    ActivationCharacterization,
    ActivationSpec,
    activation_specs,
    cauchy_riemann_residual,
    characterize_activation,
    complex_grid,
)


def _write_activation_report(
    output_dir: Path,
    characterization: ActivationCharacterization,
    *,
    plot_path: Path | None,
) -> None:
    lines = [
        f"# {characterization.name}",
        "",
        f"- Grid: `{characterization.grid_size} x {characterization.grid_size}`",
        f"- Extent: `[-{characterization.extent}, {characterization.extent}]`",
        f"- Finite output fraction: `{characterization.finite_fraction:.6f}`",
        f"- Blow-up fraction: `{characterization.blowup_fraction:.6f}`",
        f"- Max `|f(z)|`: `{characterization.max_abs:.6g}`",
        f"- CR residual median: `{characterization.cr_median:.6g}`",
        f"- CR residual p95: `{characterization.cr_p95:.6g}`",
        f"- CR residual max: `{characterization.cr_max:.6g}`",
        "",
        "## Edge Definition",
        "",
        characterization.edge_definition,
        "",
        "## Singularities / Blow-Ups",
        "",
        characterization.singularity_notes,
        "",
        "## Gradient Norms At Init (full reference MLP)",
        "",
        f"- Mean: `{characterization.gradient_norm_mean:.6g}`",
        f"- Std: `{characterization.gradient_norm_std:.6g}`",
        f"- Min: `{characterization.gradient_norm_min:.6g}`",
        f"- Max: `{characterization.gradient_norm_max:.6g}`",
        "",
        "## Activation Jacobian Norms (intrinsic, no MLP)",
        "",
        f"- Mean: `{characterization.jacobian_norm_mean:.6g}`",
        f"- Std: `{characterization.jacobian_norm_std:.6g}`",
        f"- Min: `{characterization.jacobian_norm_min:.6g}`",
        f"- Max: `{characterization.jacobian_norm_max:.6g}`",
    ]
    if plot_path is not None:
        lines.extend(["", "## Domain Plots", "", f"![plots]({plot_path.name})"])
    (output_dir / f"{characterization.name}.md").write_text("\n".join(lines) + "\n")


def _write_comparison(output_dir: Path, rows: list[ActivationCharacterization]) -> None:
    header = (
        "| Activation | finite | blow-up | max \\|f\\| | CR median | CR p95 | "
        "CR max | grad norm (MLP) | jacobian norm (intrinsic) |"
    )
    separator = "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |"
    table = [header, separator]
    for row in rows:
        table.append(
            " | ".join(
                [
                    f"| `{row.name}`",
                    f"{row.finite_fraction:.4f}",
                    f"{row.blowup_fraction:.4f}",
                    f"{row.max_abs:.4g}",
                    f"{row.cr_median:.4g}",
                    f"{row.cr_p95:.4g}",
                    f"{row.cr_max:.4g}",
                    f"{row.gradient_norm_mean:.4g}",
                    f"{row.jacobian_norm_mean:.4g} |",
                ]
            )
        )

    markdown = [
        "# Activation Characterization Comparison",
        "",
        "Generated by `uv run python scripts/characterize_activations.py`.",
        "",
        *table,
        "",
        "## Reading these numbers",
        "",
        "- **CR residual** is the Cauchy-Riemann violation magnitude on the sampled",
        "  grid. Low median + low p95 means *locally* close to holomorphic; a large",
        "  `CR max` flags grid cells that touched a singularity or a sharp ridge.",
        "  Holomorphy is not proven by small residuals on a finite grid.",
        "- **`complex_tanh`** is meromorphic with poles at `z = i*pi*(k + 1/2)`.",
        "  The default extent (`3.0`) brackets the first pair of poles at",
        "  `+/- i*pi/2 ~= +/- 1.5708i`, which is why `CR max` and `max |f|` are",
        "  large while `CR p95` stays small. This is the Liouville trade-off the",
        "  project is built around, made visible.",
        "- **`grad norm (MLP)`** is the total parameter gradient norm of a fixed",
        "  reference `ComplexMLP` driven by a fixed input distribution. It is",
        "  scaffold-confounded - useful for ranking activations on a *common*",
        "  model, not as the activation's intrinsic Jacobian magnitude.",
        "- **`jacobian norm (intrinsic)`** is the activation alone: mean of",
        "  `|d/dz_bar (|f(z)|^2)|` over uniformly sampled `z` in the same box",
        "  as the CR grid, with no MLP layers around it. Compare side-by-side",
        "  with `grad norm (MLP)` to see how much of the model-level signal is",
        "  the activation versus the surrounding linear layers.",
    ]
    (output_dir / "comparison.md").write_text("\n".join(markdown) + "\n")
    (output_dir / "comparison.json").write_text(
        json.dumps([row.to_dict() for row in rows], indent=2, sort_keys=True) + "\n"
    )


def _plot_activation(
    output_dir: Path,
    spec: ActivationSpec,
    *,
    grid_size: int,
    extent: float,
) -> Path:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    z, x_values, y_values = complex_grid(grid_size=grid_size, extent=extent)
    outputs = spec.function(z)
    dx = float(x_values[1] - x_values[0])
    dy = float(y_values[1] - y_values[0])
    cr_residual = cauchy_riemann_residual(outputs, dx=dx, dy=dy)
    extent_tuple = (-extent, extent, -extent, extent)

    fig, axes = plt.subplots(1, 3, figsize=(12.0, 3.4), constrained_layout=True)
    panels = [
        (torch.log10(outputs.abs().clamp_min(1e-12)), "log10 |f(z)|"),
        (torch.angle(outputs), "arg f(z)"),
        (torch.log10(cr_residual.clamp_min(1e-12)), "log10 CR residual"),
    ]
    for axis, (values, title) in zip(axes, panels, strict=True):
        image = axis.imshow(
            values.detach().cpu().numpy(),
            origin="lower",
            extent=extent_tuple,
            aspect="equal",
        )
        axis.set_title(title)
        axis.set_xlabel("Re z")
        axis.set_ylabel("Im z")
        fig.colorbar(image, ax=axis, fraction=0.046, pad=0.04)

    plot_path = output_dir / f"{spec.name}.png"
    fig.savefig(plot_path, dpi=180)
    plt.close(fig)
    return plot_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("notebooks/activation_characterization"),
    )
    parser.add_argument("--grid-size", type=int, default=121)
    parser.add_argument("--extent", type=float, default=3.0)
    parser.add_argument("--gradient-seeds", type=int, default=5)
    parser.add_argument("--no-plots", action="store_true")
    args = parser.parse_args()

    output_dir: Path = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    seeds = tuple(range(args.gradient_seeds))

    rows: list[ActivationCharacterization] = []
    for spec in activation_specs():
        characterization = characterize_activation(
            spec,
            grid_size=args.grid_size,
            extent=args.extent,
            gradient_seeds=seeds,
        )
        plot_path = None
        if not args.no_plots:
            plot_path = _plot_activation(
                output_dir,
                spec,
                grid_size=args.grid_size,
                extent=args.extent,
            )
        _write_activation_report(output_dir, characterization, plot_path=plot_path)
        rows.append(characterization)

    _write_comparison(output_dir, rows)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
